# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sns_type', models.CharField(choices=[('blog', '\ube14\ub85c\uadf8'), ('facebook', '\ud398\uc774\uc2a4\ubd81'), ('instagram', '\uc778\uc2a4\ud0c0\uadf8\ub7a8'), ('kakaostroy', '\uce74\uce74\uc624\uc2a4\ud1a0\ub9ac')], max_length=15)),
                ('sns_additional_info', models.CharField(choices=[('individual', '\uac1c\uc778'), ('page', '\ud398\uc774\uc9c0')], max_length=15)),
                ('sex', models.CharField(choices=[('male', '\ub0a8\uc790'), ('female', '\uc5ec\uc790')], max_length=15)),
                ('is_url_open', models.BooleanField(default=True)),
                ('sns_url', models.URLField(blank=True, null=True)),
                ('follower_num', models.CharField(blank=True, max_length=255, null=True)),
                ('message_to_buyer', models.TextField(blank=True, null=True)),
                ('oneline_intro', models.CharField(blank=True, max_length=255, null=True)),
                ('description', django_summernote.fields.SummernoteTextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('manuscript_available', models.BooleanField(default=True)),
                ('manuscript_price', models.PositiveIntegerField(default=0)),
                ('highrank_available', models.BooleanField(default=False)),
                ('highrank_price', models.PositiveIntegerField(default=0)),
                ('working_period', models.PositiveIntegerField(default=0)),
                ('message_to_admin', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('all', '\uc804\uccb4'), ('it', 'IT/\uc778\ud130\ub137'), ('fasion', '\ud328\uc158/\ubdf0\ud2f0'), ('travel', '\uc5ec\ud589/\uc219\ubc15'), ('game', '\uac8c\uc784'), ('car', '\uc790\ub3d9\ucc28'), ('financial', '\uc7ac\ud14c\ud06c/\uae08\uc735'), ('study', '\ucde8\uc5c5/\ud559\uc5c5'), ('baby', '\uc721\uc544'), ('pet', '\ubc18\ub824\ub3d9\ubb3c'), ('media', '\ubbf8\ub514\uc5b4/\uc601\ud654'), ('interior', '\uc778\ud14c\ub9ac\uc5b4'), ('food', '\ub9db\uc9d1/\uc2dd\ud488'), ('music', '\uc74c\uc545'), ('diet', '\ub2e4\uc774\uc5b4\ud2b8'), ('health', '\ub9ac\ube59/\uac74\uac15'), ('life', '\uc77c\uc0c1/\uc0dd\ud65c'), ('picture', '\uc0ac\uc9c4'), ('love', '\uacb0\ud63c/\uc5f0\uc560'), ('sports', '\uc2a4\ud3ec\uce20/\ub808\uc800')], max_length=15)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptags', to='contenttypes.ContentType')),
            ],
        ),
    ]
