# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='socialup_gauge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
