# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_producttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='tag',
            field=models.CharField(choices=[('it', 'IT/\uc778\ud130\ub137'), ('fasion', '\ud328\uc158/\ubdf0\ud2f0'), ('travel', '\uc5ec\ud589/\uc219\ubc15'), ('game', '\uac8c\uc784'), ('car', '\uc790\ub3d9\ucc28'), ('financial', '\uc7ac\ud14c\ud06c/\uae08\uc735'), ('study', '\ucde8\uc5c5/\ud559\uc5c5'), ('baby', '\uc721\uc544'), ('pet', '\ubc18\ub824\ub3d9\ubb3c'), ('media', '\ubbf8\ub514\uc5b4/\uc601\ud654'), ('interior', '\uc778\ud14c\ub9ac\uc5b4'), ('food', '\ub9db\uc9d1/\uc2dd\ud488'), ('music', '\uc74c\uc545'), ('diet', '\ub2e4\uc774\uc5b4\ud2b8'), ('health', '\ub9ac\ube59/\uac74\uac15'), ('life', '\uc77c\uc0c1/\uc0dd\ud65c'), ('picture', '\uc0ac\uc9c4'), ('love', '\uacb0\ud63c/\uc5f0\uc560'), ('sports', '\uc2a4\ud3ec\uce20/\ub808\uc800')], max_length=15),
        ),
    ]
