# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 14:18
from __future__ import unicode_literals

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_auto_20160713_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='refund',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
