# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_auto_20160726_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
