# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('markets', '0007_variation_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnsUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='influence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
