# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('markets', '0008_auto_20160902_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('all', '\uc804 \uc5f0\ub839'), ('10', '10\ub300'), ('20', '20\ub300'), ('30', '30\ub300'), ('40', '40\ub300 \uc774\uc0c1'), ('gender', '\ub0a8\uc5ec \ubaa8\ub450'), ('male', '\ub0a8'), ('female', '\uc5ec')], max_length=15)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='SnsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('all', '\uc804\uccb4'), ('it', 'IT/\uc778\ud130\ub137'), ('fasion', '\ud328\uc158/\ubdf0\ud2f0'), ('travel', '\uc5ec\ud589/\uc219\ubc15'), ('game', '\uac8c\uc784'), ('car', '\uc790\ub3d9\ucc28'), ('financial', '\uc7ac\ud14c\ud06c/\uae08\uc735'), ('study', '\ucde8\uc5c5/\ud559\uc5c5'), ('baby', '\uc721\uc544'), ('pet', '\ubc18\ub824\ub3d9\ubb3c'), ('media', '\ubbf8\ub514\uc5b4/\uc601\ud654'), ('interior', '\uc778\ud14c\ub9ac\uc5b4'), ('food', '\ub9db\uc9d1/\uc2dd\ud488'), ('music', '\uc74c\uc545'), ('diet', '\ub2e4\uc774\uc5b4\ud2b8'), ('health', '\ub9ac\ube59/\uac74\uac15'), ('life', '\uc77c\uc0c1/\uc0dd\ud65c'), ('picture', '\uc0ac\uc9c4'), ('love', '\uacb0\ud63c/\uc5f0\uc560'), ('sports', '\uc2a4\ud3ec\uce20/\ub808\uc800')], max_length=15)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterField(
            model_name='producttag',
            name='tag',
            field=models.CharField(choices=[('all', '\uc804\uccb4'), ('it', 'IT/\uc778\ud130\ub137'), ('fasion', '\ud328\uc158/\ubdf0\ud2f0'), ('travel', '\uc5ec\ud589/\uc219\ubc15'), ('game', '\uac8c\uc784'), ('car', '\uc790\ub3d9\ucc28'), ('financial', '\uc7ac\ud14c\ud06c/\uae08\uc735'), ('study', '\ucde8\uc5c5/\ud559\uc5c5'), ('baby', '\uc721\uc544'), ('pet', '\ubc18\ub824\ub3d9\ubb3c'), ('media', '\ubbf8\ub514\uc5b4/\uc601\ud654'), ('interior', '\uc778\ud14c\ub9ac\uc5b4'), ('food', '\ub9db\uc9d1/\uc2dd\ud488'), ('music', '\uc74c\uc545'), ('diet', '\ub2e4\uc774\uc5b4\ud2b8'), ('health', '\ub9ac\ube59/\uac74\uac15'), ('life', '\uc77c\uc0c1/\uc0dd\ud65c'), ('picture', '\uc0ac\uc9c4'), ('love', '\uacb0\ud63c/\uc5f0\uc560'), ('sports', '\uc2a4\ud3ec\uce20/\ub808\uc800')], max_length=15),
        ),
    ]
