# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0009_auto_20160902_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='command',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='refund',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttarget',
            name='target',
            field=models.CharField(choices=[('all', '\uc804 \uc5f0\ub839'), ('10', '10\ub300'), ('20', '20\ub300'), ('30', '30\ub300'), ('40', '40\ub300 \uc774\uc0c1'), ('gender', '\ub0a8\uc5ec \ubaa8\ub450'), ('male', '\ub0a8\uc131'), ('female', '\uc5ec\uc131')], max_length=15),
        ),
    ]
