# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_auto_20160902_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
