# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0011_auto_20160904_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='workContent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='workingDay',
        ),
    ]
