# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0012_auto_20160904_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snstype',
            name='type',
            field=models.CharField(choices=[('all', '\uc804\uccb4'), ('blog', '\ube14\ub85c\uadf8'), ('facebook', '\ud398\uc774\uc2a4\ubd81'), ('instagram', '\uc778\uc2a4\ud0c0\uadf8\ub7a8'), ('kakaostroy', '\uce74\uce74\uc624\uc2a4\ud1a0\ub9ac'), ('twitter', '\ud2b8\uc704\ud130'), ('cafe', '\uce74\ud398'), ('afreecatv', '\uc544\ud504\ub9ac\uce74TV'), ('pola', '\ud3f4\ub77c'), ('etc', '\uae30\ud0c0')], max_length=15),
        ),
    ]
