# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0014_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_tpye', models.CharField(choices=[('hd', 'HD'), ('sd', 'SD'), ('micro', 'Micro')], default='hd', max_length=20)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('width', models.CharField(blank=True, max_length=20, null=True)),
                ('media', models.ImageField(blank=True, height_field='height', null=True, upload_to=markets.models.thumbnail_location, width_field='width')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='snstype',
            name='type',
            field=models.CharField(choices=[('all', '\uc804\uccb4'), ('blog', '\ube14\ub85c\uadf8'), ('facebook', '\ud398\uc774\uc2a4\ubd81'), ('instagram', '\uc778\uc2a4\ud0c0\uadf8\ub7a8'), ('kakaostroy', '\uce74\uce74\uc624\uc2a4\ud1a0\ub9ac'), ('twitter', '\ud2b8\uc704\ud130'), ('cafe', '\uce74\ud398'), ('afreecatv', '\uc544\ud504\ub9ac\uce74TV'), ('pholar', '\ud3f4\ub77c'), ('etc', '\uae30\ud0c0')], max_length=15),
        ),
    ]
