# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0015_auto_20161103_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productthumbnail',
            old_name='thumb_tpye',
            new_name='thumb_type',
        ),
    ]
