# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointmerchantid',
            name='user',
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='PointMerchantId',
        ),
    ]
