# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20160728_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
