# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20160729_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointhistory',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
