# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20160726_1947'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0005_auto_20160730_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='created', max_length=120)),
                ('order_total', models.PositiveIntegerField(default=0)),
                ('order_id', models.CharField(max_length=120, unique=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
