# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20160807_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
