# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0007_variation_is_default'),
        ('accounts', '0007_myuser_access_token'),
        ('billing', '0010_auto_20160808_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Variation')),
            ],
        ),
        migrations.CreateModel(
            name='ProductManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('progress', 'Progress'), ('complete', 'Complete'), ('finish', 'Finish'), ('cancel', 'Cancel')], default='ready', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='billing.ProductList')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller')),
            ],
        ),
        migrations.AddField(
            model_name='productlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.ProductManage'),
        ),
    ]
