# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0014_product_is_active'),
        ('billing', '0012_order_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmanage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='markets.Product'),
        ),
    ]
