# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_myuser_access_token'),
        ('billing', '0013_productmanage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('processing', 'Processing'), ('finished', 'Finished')], default='created', max_length=120),
        ),
    ]
