# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='message_to_bad_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
