# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-27 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactRoom',
            new_name='Contact',
        ),
    ]
