# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 13:41
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('media', models.ImageField(blank=True, null=True, upload_to=accounts.models.download_profile_location)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyUserThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_type', models.CharField(choices=[('hd', 'HD'), ('sd', 'SD'), ('micro', 'Micro')], default='hd', max_length=20)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('width', models.CharField(blank=True, max_length=20, null=True)),
                ('media', models.ImageField(blank=True, height_field='height', null=True, upload_to=accounts.models.thumbnail_location, width_field='width')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField(default=0)),
                ('is_possible_profit', models.BooleanField(default=False)),
                ('is_expect_profit', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxWorking', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=120, null=True)),
                ('account_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(blank=True, choices=[('\uae30\uc5c5\uc740\ud589', '\uae30\uc5c5\uc740\ud589'), ('\uad6d\ubbfc\uc740\ud589', '\uad6d\ubbfc\uc740\ud589'), ('\uc678\ud658\uc740\ud589', '\uc678\ud658\uc740\ud589'), ('\uc218\ud611\uc911\uc559\ud68c', '\uc218\ud611\uc911\uc559\ud68c'), ('\ub18d\ud611\uc911\uc559\ud68c', '\ub18d\ud611\uc911\uc559\ud68c'), ('\uc6b0\ub9ac\uc740\ud589', '\uc6b0\ub9ac\uc740\ud589'), ('SC\uc81c\uc77c\uc740\ud589', 'SC\uc81c\uc77c\uc740\ud589'), ('\ub300\uad6c\uc740\ud589', '\ub300\uad6c\uc740\ud589'), ('\ubd80\uc0b0\uc740\ud589', '\ubd80\uc0b0\uc740\ud589'), ('\uad11\uc8fc\uc740\ud589', '\uad11\uc8fc\uc740\ud589'), ('\uc804\ubd81\uc740\ud589', '\uc804\ubd81\uc740\ud589'), ('\uacbd\ub0a8\uc740\ud589', '\uacbd\ub0a8\uc740\ud589'), ('\ud55c\uad6d\uc528\ud2f0\uc740\ud589', '\ud55c\uad6d\uc528\ud2f0\uc740\ud589'), ('\uc6b0\uccb4\uad6d', '\uc6b0\uccb4\uad6d'), ('\ud558\ub098\uc740\ud589', '\ud558\ub098\uc740\ud589'), ('\ud1b5\ud569\uc2e0\ud55c\uc740\ud589(\uc2e0\ud55c,\uc870\ud765\uc740\ud589)', '\ud1b5\ud569\uc2e0\ud55c\uc740\ud589(\uc2e0\ud55c,\uc870\ud765\uc740\ud589)'), ('\uc720\uc548\ud0c0\uc99d\uad8c(\uad6c \ub3d9\uc591\uc99d\uad8c)', '\uc720\uc548\ud0c0\uc99d\uad8c(\uad6c \ub3d9\uc591\uc99d\uad8c)'), ('\ud604\ub300\uc99d\uad8c', '\ud604\ub300\uc99d\uad8c'), ('\ubbf8\ub798\uc5d0\uc14b\uc99d\uad8c', '\ubbf8\ub798\uc5d0\uc14b\uc99d\uad8c'), ('\ud55c\uad6d\ud22c\uc790\uc99d\uad8c', '\ud55c\uad6d\ud22c\uc790\uc99d\uad8c'), ('\uc6b0\ub9ac\ud22c\uc790\uc99d\uad8c', '\uc6b0\ub9ac\ud22c\uc790\uc99d\uad8c'), ('\ud558\uc774\ud22c\uc790\uc99d\uad8c', '\ud558\uc774\ud22c\uc790\uc99d\uad8c'), ('HMC\ud22c\uc790\uc99d\uad8c', 'HMC\ud22c\uc790\uc99d\uad8c'), ('SK\uc99d\uad8c', 'SK\uc99d\uad8c'), ('\ub300\uc2e0\uc99d\uad8c', '\ub300\uc2e0\uc99d\uad8c'), ('\ud558\ub098\ub300\ud22c\uc99d\uad8c', '\ud558\ub098\ub300\ud22c\uc99d\uad8c'), ('\uad7f\ubaa8\ub2dd\uc2e0\ud55c\uc99d\uad8c', '\uad7f\ubaa8\ub2dd\uc2e0\ud55c\uc99d\uad8c'), ('\ub3d9\ubd80\uc99d\uad8c', '\ub3d9\ubd80\uc99d\uad8c'), ('\uc720\uc9c4\ud22c\uc790\uc99d\uad8c', '\uc720\uc9c4\ud22c\uc790\uc99d\uad8c'), ('\uba54\ub9ac\uce20\uc99d\uad8c', '\uba54\ub9ac\uce20\uc99d\uad8c'), ('\uc2e0\uc601\uc99d\uad8c', '\uc2e0\uc601\uc99d\uad8c'), ('\ud55c\uad6d\uc528\ud2f0\uc740\ud589(\ud55c\ubbf8\uc740\ud589)', '\ud55c\uad6d\uc528\ud2f0\uc740\ud589 (\ud55c\ubbf8\uc740\ud589)')], max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller')),
            ],
        ),
        migrations.AddField(
            model_name='profit',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller'),
        ),
    ]
