# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:34
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.download_profile_location),
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
