# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-23 10:06
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='account_copy',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.download_seller_account_location),
        ),
        migrations.AlterField(
            model_name='seller',
            name='business_license',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.download_seller_license_location),
        ),
        migrations.AlterField(
            model_name='seller',
            name='type',
            field=models.CharField(choices=[('individual', '\uac1c\uc778'), ('personal_business', '\uac1c\uc778\uc0ac\uc5c5\uc790'), ('corporate_business', '\ubc95\uc778\uc0ac\uc5c5\uc790'), ('confirming_status', '\ud655\uc778\uc911')], default='individual', max_length=20, null=True),
        ),
    ]
