# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170223_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='type',
            field=models.CharField(choices=[('individual', '\uac1c\uc778'), ('personal_business', '\uac1c\uc778\uc0ac\uc5c5\uc790'), ('corporate_business', '\ubc95\uc778\uc0ac\uc5c5\uc790'), ('confirming_personal', '\ud655\uc778\uc911(\uac1c\uc778\uc0ac\uc5c5\uc790)'), ('confirming_corporate', '\ud655\uc778\uc911(\ubc95\uc778\uc0ac\uc5c5\uc790)')], default='individual', max_length=20, null=True),
        ),
    ]
