# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160711_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
