# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160723_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
