# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_myuser_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='access_token',
        ),
    ]
