# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_myuser_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField(default=0)),
                ('is_possible_profit', models.BooleanField(default=False)),
                ('is_expect_profit', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller')),
            ],
        ),
    ]
