# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
