# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('blog', '\ube14\ub85c\uadf8'), ('facebook', '\ud398\uc774\uc2a4\ubd81'), ('instagram', '\uc778\uc2a4\ud0c0\uadf8\ub7a8'), ('kakaostroy', '\uce74\uce74\uc624\uc2a4\ud1a0\ub9ac'), ('cafe', '\uce74\ud398'), ('twitter', '\ud2b8\uc704\ud130'), ('pola', '\ud3f4\ub77c'), ('afreeca', '\uc544\ud504\ub9ac\uce74TV'), ('etc', '\uae30\ud0c0')], max_length=30)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_confirm', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SocialAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics', models.CharField(blank=True, max_length=20)),
                ('outcome', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
