# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('contents_satisfy', models.CharField(choices=[('good', 'good'), ('neutral', 'neutral'), ('bad', 'bad')], default='good', max_length=10)),
                ('ad_satisfy', models.CharField(choices=[('good', 'good'), ('neutral', 'neutral'), ('bad', 'bad')], default='good', max_length=10)),
                ('kind_satisfy', models.CharField(choices=[('good', 'good'), ('neutral', 'neutral'), ('bad', 'bad')], default='good', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.OrderItem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
